Repository 8-Sprinters/ListyWave-back, pull requests merged in 2024-04, with the labels that each got.

#244 feat: 리스트 생성 시 히스토리로도 저장되도록 구현
  src/main/java/com/listywave/list/application/service/ListService.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTestHelper.java
Labels: 기능

#247 fix: 리스트 상세 조회 시, isCollected가 항상 false로 반환되는 버그 해결
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
Labels: 버그

#248 feat: 콜라보레이터를 지정하면 콜라보레이터 지정 당한 대상들에게 모두 알림이 가도록 구현
  src/main/java/com/listywave/alarm/application/domain/AlarmEvent.java
  src/main/java/com/listywave/alarm/application/domain/AlarmType.java
  src/main/java/com/listywave/alarm/application/dto/AlarmListResponse.java
  src/main/java/com/listywave/alarm/application/dto/FindAlarmResponse.java
  src/main/java/com/listywave/alarm/repository/custom/CustomAlarmRepository.java
  src/main/java/com/listywave/alarm/repository/custom/impl/CustomAlarmRepositoryImpl.java
  src/main/java/com/listywave/collaborator/application/service/CollaboratorService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTest.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/comment/CommentAcceptanceTestHelper.java
Labels: 기능, 테스트

#250 feat: scheduler 이용하여 30일 지난 알림 삭제 주기적으로 삭제 기능 구현
  src/main/java/com/listywave/ListywaveApplication.java
  src/main/java/com/listywave/alarm/application/service/AlarmSchedulerService.java
  src/main/java/com/listywave/alarm/repository/custom/impl/CustomAlarmRepositoryImpl.java
Labels: 기능

#249 feat: 나의 모든 알림 읽기 API 구현
  src/main/java/com/listywave/alarm/application/service/AlarmService.java
  src/main/java/com/listywave/alarm/presentation/controller/AlarmController.java
  src/main/java/com/listywave/alarm/repository/AlarmRepository.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTest.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTestHelper.java
Labels: 기능, 테스트
