Repository 8-Sprinters/ListyWave-back, pull requests merged in 2024-01, with the labels that each got.

#6 chore: 작업 환경 셋팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/listywave/ListywaveApplication.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/listywave/ListywaveApplicationTests.java
  src/test/resources/application-test.yml
Labels: 환경설정

#9 chore: IntelliJ에서 커밋 시에 자동으로 type을 prefix, 이슈 번호를 postfix로 추가해주는 기능 구현
  .githooks/commit-msg
  Makefile
  README.md
Labels: 환경설정

#16 feat: Entity 작성
  src/main/java/com/listywave/ListywaveApplication.java
  src/main/java/com/listywave/collaborator/domain/Collaborator.java
  src/main/java/com/listywave/common/BaseEntity.java
  src/main/java/com/listywave/list/domain/Category.java
  src/main/java/com/listywave/list/domain/CategoryType.java
  src/main/java/com/listywave/list/domain/Comment.java
  src/main/java/com/listywave/list/domain/Item.java
  src/main/java/com/listywave/list/domain/List.java
  src/main/java/com/listywave/list/domain/Reply.java
  src/main/java/com/listywave/user/domain/Role.java
  src/main/java/com/listywave/user/domain/User.java
  src/main/java/com/listywave/user/vo/Nickname.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/listywave/user/vo/NicknameTest.java
  src/test/resources/application-test.yml
Labels: 기능

#22 infra: 백엔드 CI 및 개발 서버 CD 구축
  .github/workflows/ci.yml
  .github/workflows/dev-cd.yml
  src/main/java/com/listywave/user/vo/Nickname.java
  src/main/resources/application.yml
  src/test/java/com/listywave/user/vo/NicknameTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 인프라

#24 feat: 도메인 레벨 validate 구현
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/domain/Comment.java
  src/main/java/com/listywave/list/domain/Item.java
  src/main/java/com/listywave/list/domain/List.java
  src/main/java/com/listywave/list/domain/Reply.java
  src/main/java/com/listywave/list/vo/Content.java
  src/main/java/com/listywave/list/vo/ItemComment.java
  src/main/java/com/listywave/list/vo/ItemImageUrl.java
  src/main/java/com/listywave/list/vo/ItemLink.java
  src/main/java/com/listywave/list/vo/ItemTitle.java
  src/main/java/com/listywave/list/vo/Labels.java
  src/main/java/com/listywave/list/vo/ListDescription.java
  src/main/java/com/listywave/list/vo/ListTitle.java
  src/main/java/com/listywave/user/domain/User.java
  src/main/java/com/listywave/user/vo/BackgroundImageUrl.java
  src/main/java/com/listywave/user/vo/Description.java
  src/main/java/com/listywave/user/vo/Nickname.java
  src/main/java/com/listywave/user/vo/ProfileImageUrl.java
  src/test/java/com/listywave/user/vo/BackgroundImageUrlTest.java
Labels: 기능
