Repository 8-Sprinters/ListyWave-back, pull requests merged in 2024-06, with the labels that each got.

#265 feat : ElasticSearch 이용하여 사용자 검색 API 마이그레이션
  build.gradle
  docker-es/.dockerignore
  docker-es/.env
  docker-es/.gitattributes
  docker-es/LICENSE
  docker-es/docker-compose.yml
  docker-es/elasticsearch/Dockerfile
  docker-es/elasticsearch/config/elasticsearch.yml
  docker-es/kibana/Dockerfile
  docker-es/kibana/config/kibana.yml
  docker-es/logstash/Dockerfile
  docker-es/logstash/config/logstash.yml
  docker-es/logstash/config/pipelines.yml
  docker-es/logstash/mysql-connector-j-8.0.33.jar
  docker-es/logstash/pipeline/logstash.conf
  src/main/java/com/listywave/common/config/ElasticSearchConfig.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/user/application/domain/UserDocument.java
  src/main/java/com/listywave/user/application/dto/search/UserElasticSearchResponse.java
  src/main/java/com/listywave/user/application/dto/search/UserElasticSearchResult.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
  src/main/resources/application.yml
  src/main/resources/elastic/user/es-mapping.json
  src/main/resources/elastic/user/es-setting.json
  src/test/resources/application.yml
Labels: 성능, 기능, 인프라, 환경설정

#273 infra: 모니터링 대시보드 구축을 위한 메트릭 및 의존성 추가
  build.gradle
  src/main/resources/application.yml
Labels: 인프라, 급함

#278 feat: 관리자와 헷갈릴만한 닉네임은 허용하지 않도록 검증
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/application/vo/Nickname.java
  src/main/java/com/listywave/user/repository/user/UserRepository.java
  src/test/java/com/listywave/acceptance/user/UserAcceptanceTest.java
  src/test/java/com/listywave/user/application/vo/NicknameTest.java
Labels: 기능

#279 refactor: 트랜딩 TOP10 조회 API 정렬기준 변경
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTest.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/reply/ReplyAcceptanceTest.java
Labels: 기능, 리팩터링, 테스트
