Repository 8-Sprinters/ListyWave-back, pull requests merged in 2024-02, with the labels that each got.

#29 feat: 카카오 Oauth 로그인 기능 구현
  build.gradle
  src/main/java/com/listywave/ListywaveApplication.java
  src/main/java/com/listywave/auth/config/HttpInterfaceConfig.java
  src/main/java/com/listywave/auth/config/OAuthServerTypeConverter.java
  src/main/java/com/listywave/auth/controller/AuthController.java
  src/main/java/com/listywave/auth/domain/JwtManager.java
  src/main/java/com/listywave/auth/domain/OauthServerType.java
  src/main/java/com/listywave/auth/domain/kakao/KakaoOauthClient.java
  src/main/java/com/listywave/auth/domain/kakao/KakaoOauthConfig.java
  src/main/java/com/listywave/auth/domain/kakao/KakaoRedirectUriProvider.java
  src/main/java/com/listywave/auth/infra/kakao/KakaoOauthApiClient.java
  src/main/java/com/listywave/auth/infra/kakao/response/KakaoMember.java
  src/main/java/com/listywave/auth/infra/kakao/response/KakaoTokenResponse.java
  src/main/java/com/listywave/auth/service/AuthService.java
  src/main/java/com/listywave/auth/service/response/LoginResponse.java
  src/main/java/com/listywave/common/config/WebConfig.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/common/exception/GlobalExceptionHandler.java
  src/main/java/com/listywave/user/domain/Role.java
  src/main/java/com/listywave/user/domain/User.java
  src/main/java/com/listywave/user/repository/UserRepository.java
  src/main/java/com/listywave/user/vo/Nickname.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/listywave/auth/domain/OauthServerTypeTest.java
  src/test/resources/application.yml
Labels: 기능

#44 chore: dev 서버 ddl-auto 옵션 수정 및 더미 데이터를 위한 data.sql 작성
  src/main/java/com/listywave/common/converter/BooleanConverter.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/listywave/ListywaveApplicationTest.java
  src/test/resources/application.yml
Labels: 기능, 인프라, 환경설정

#47 feat: 회원 정보 조회 기능 구현
  src/main/java/com/listywave/auth/presentation/dto/LoginResponse.java
  src/main/java/com/listywave/common/BaseEntity.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/dto/UserInfoResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능

#48 feat: 모든 회원 정보 조회 API 구현
  .github/workflows/ci.yml
  src/main/java/com/listywave/user/application/dto/AllUserResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능

#50 feat: 리스트 상세 조회 기능 구현
  src/main/java/com/listywave/collaborator/domain/Collaborator.java
  src/main/java/com/listywave/collaborator/domain/repository/CollaboratorRepository.java
  src/main/java/com/listywave/list/application/domain/Item.java
  src/main/java/com/listywave/list/application/domain/Label.java
  src/main/java/com/listywave/list/application/domain/Lists.java
  src/main/java/com/listywave/list/application/dto/ListCreateCommand.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/ListRepository.java
Labels: 기능

#53 feat: 커서 페이지네이션 이용한 피드 전체리스트 API 구현
  build.gradle
  src/main/java/com/listywave/common/config/EnumMappingConfig.java
  src/main/java/com/listywave/common/config/QuerydslConfig.java
  src/main/java/com/listywave/list/application/domain/CategoryType.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/dto/response/CategoryTypeResponse.java
  src/main/java/com/listywave/user/application/dto/FeedListsResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/presentation/dto/response/AllUserListsResponse.java
  src/main/java/com/listywave/user/repository/UserRepository.java
  src/main/java/com/listywave/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/listywave/user/repository/custom/impl/UserRepositoryImpl.java
  src/main/resources/application.yml
Labels: 기능, 리팩터링, 환경설정

#54 feat: 댓글/답글 CRD API 구현
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/domain/Comment.java
  src/main/java/com/listywave/list/application/domain/Reply.java
  src/main/java/com/listywave/list/application/dto/ReplyDeleteCommand.java
  src/main/java/com/listywave/list/application/dto/response/CommentCreateResponse.java
  src/main/java/com/listywave/list/application/dto/response/CommentFindResponse.java
  src/main/java/com/listywave/list/application/dto/response/ReplyCreateResponse.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/list/presentation/dto/request/ListCreateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/ReplyCreateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/comment/CommentCreateRequest.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/ReplyRepository.java
  src/main/java/com/listywave/user/repository/UserRepository.java
Labels: 기능

#57 feat: s3 버킷 endpoint CloudFront 도메인으로 변경 및 profile별 동적 폴더 구조 되도록 구성 (#34)
  src/main/java/com/listywave/common/constants/EnvironmentConstants.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/user/repository/custom/impl/UserRepositoryImpl.java
Labels: 기능, 인프라

#71 feat: 팔로잉 목록 조회 API 구현
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/common/util/UserUtil.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/user/application/domain/Follow.java
  src/main/java/com/listywave/user/application/dto/AllUserListsResponse.java
  src/main/java/com/listywave/user/application/dto/FollowingsResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/follow/FollowRepository.java
  src/main/java/com/listywave/user/repository/user/UserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 기능

#77 feat: 탐색 페이지 트랜딩 리스트 조회 API 구현
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/list/application/domain/Lists.java
  src/main/java/com/listywave/list/application/dto/response/CategoryTypeResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListCreateResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CategoryController.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/ListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
Labels: 기능

#70 feat: 카카오 로그아웃 API 구현
  src/main/java/com/listywave/auth/application/domain/kakao/KakaoOauthClient.java
  src/main/java/com/listywave/auth/application/dto/LoginResponse.java
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/auth/config/OAuthServerTypeConverter.java
  src/main/java/com/listywave/auth/infra/kakao/KakaoOauthApiClient.java
  src/main/java/com/listywave/auth/infra/kakao/response/KakaoLogoutResponse.java
  src/main/java/com/listywave/auth/presentation/AuthController.java
  src/main/java/com/listywave/common/config/WebConfig.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/service/UserService.java
Labels: 기능

#72 fix: AccessToken 만료 시간 및 응답 방식 변경
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/java/com/listywave/auth/application/dto/LoginResponse.java
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/auth/presentation/AuthController.java
Labels: 리팩터링

#78 feat: 팔로우 해제 API 구현
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/follow/FollowRepository.java
Labels: 기능

#82 feat: 최신 리스트 10개 조회 API 구현
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
Labels: 기능

#81 feat: 탐색페이지 사용자 추천 리스트 API 구현
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/user/application/dto/AllUserListsResponse.java
  src/main/java/com/listywave/user/application/dto/FeedListsResponse.java
  src/main/java/com/listywave/user/application/dto/RecommendUsersResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 기능

#85 fix: 팔로잉 조회 API 명세 변경에 따른 로직 변경
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능

#86 feat: 팔로워 조회 API 구현
  src/main/java/com/listywave/user/application/dto/FollowersResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/follow/FollowRepository.java
  src/main/java/com/listywave/user/repository/follow/custom/CustomFollowRepository.java
  src/main/java/com/listywave/user/repository/follow/custom/impl/CustomFollowRepositoryImpl.java
Labels: 기능

#83 feat: 리스트 삭제 API 구현
  src/main/java/com/listywave/ListywaveApplication.java
  src/main/java/com/listywave/collaborator/domain/repository/CollaboratorRepository.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/ReplyRepository.java
Labels: 기능

#88 feat: 리스트의 댓글/답글 조회 시, totalCount에 Reply의 수가 빠진 것 수정
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
Labels: 버그, 기능, 리팩터링

#89 feat: 리스트 생성시 콜라보레이터 검색 및 무한스크롤 API 구현
  src/main/java/com/listywave/collaborator/application/domain/Collaborator.java
  src/main/java/com/listywave/collaborator/application/dto/CollaboratorResponse.java
  src/main/java/com/listywave/collaborator/application/dto/CollaboratorSearchResponse.java
  src/main/java/com/listywave/collaborator/application/service/CollaboratorService.java
  src/main/java/com/listywave/collaborator/presentation/controller/CollaboratorController.java
  src/main/java/com/listywave/collaborator/repository/CollaboratorRepository.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 기능

#94 feat: 닉네임 중복 체크 API 구현
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/UserRepository.java
Labels: 기능

#95 feat: 프로필 수정 API 구현
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/dto/UserProflieUpdateCommand.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/presentation/dto/UserProfileUpdateRequest.java
Labels: 기능

#96 feat: 사용자 배경이미지, 프로필이미지 Presigned url 관련 수정 API 구현
  src/main/java/com/listywave/image/application/dto/response/ItemPresignedUrlResponse.java
  src/main/java/com/listywave/image/application/dto/response/UserPresignedUrlResponse.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/image/presentation/controller/ImageController.java
  src/main/java/com/listywave/image/presentation/dto/request/UserImageUpdateRequest.java
  src/main/java/com/listywave/image/presentation/dto/response/PresignedUrlResponse.java
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 기능, 인프라

#98 fix: 댓글 조회 버그 수정
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepository.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepositoryImpl.java
  src/main/java/com/listywave/list/repository/reply/ReplyRepository.java
Labels: 버그, 기능

#99 feat: 관련도 정렬을 제외한 리스트 검색 기능 구현
  src/main/java/com/listywave/common/util/StringUtils.java
  src/main/java/com/listywave/list/application/domain/Lists.java
  src/main/java/com/listywave/list/application/domain/SortType.java
  src/main/java/com/listywave/list/application/dto/response/ListSearchResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
Labels: 기능

#101 feat: 팔로우 여부 응답에 포함하도록 반영
  src/main/java/com/listywave/user/application/domain/Follow.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/dto/UserInfoResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/repository/follow/FollowRepository.java
Labels: 기능

#107 fix: AccessToken에 Prefix 추가
  src/main/java/com/listywave/auth/application/domain/kakao/KakaoOauthClient.java
Labels: 버그

#109 refactor: List 엔티티 이름 변경
  src/main/java/com/listywave/collaborator/application/domain/Collaborator.java
  src/main/java/com/listywave/collaborator/repository/CollaboratorRepository.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/list/application/domain/Comment.java
  src/main/java/com/listywave/list/application/domain/Item.java
  src/main/java/com/listywave/list/application/domain/Label.java
  src/main/java/com/listywave/list/application/domain/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListSearchResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/list/ListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepository.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepositoryImpl.java
  src/main/java/com/listywave/user/application/dto/AllUserListsResponse.java
  src/main/java/com/listywave/user/application/dto/FeedListsResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 리팩터링

#111 fix: Cascade 옵션 제거
  src/main/java/com/listywave/user/application/domain/Follow.java
Labels: 버그

#115 refactor: 예외 관련 리팩터링
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/common/exception/ErrorResponse.java
  src/main/java/com/listywave/common/exception/GlobalExceptionHandler.java
  src/main/java/com/listywave/common/util/UserUtil.java
  src/main/java/com/listywave/image/application/domain/ImageFileExtension.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/list/application/domain/CategoryType.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/list/ListRepository.java
  src/main/java/com/listywave/user/repository/user/UserRepository.java
Labels: 리팩터링

#116 feat: 인증 정보 Required로 반영 및 인가 기능 구현
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/java/com/listywave/list/application/domain/Comment.java
  src/main/java/com/listywave/list/application/domain/ListEntity.java
  src/main/java/com/listywave/list/application/domain/Reply.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/list/repository/reply/ReplyRepository.java
Labels: 기능

#114 fix: 콜라보레이터로 등록 된 유저가 자신의 피드에서 리스트 안보이던 문제 수정
  src/main/java/com/listywave/collaborator/repository/CollaboratorRepository.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 버그, 기능

#121 feat: 콜렉션 Enitity생성 및 콜렉트 담기 및 취소 API 구현
  src/main/java/com/listywave/collection/application/domain/Collect.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/repository/CollectionRepository.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/domain/ListEntity.java
Labels: 기능

#125 fix: kakaoAccessToken 갱신 기능 추가
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 버그

#128 feat: 내가 콜렉트한 리스트 조회하는 콜렉션 조회 API 구현 및 리펙토링
  src/main/java/com/listywave/collaborator/presentation/controller/CollaboratorController.java
  src/main/java/com/listywave/collection/application/dto/CollectionResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/repository/CollectionRepository.java
  src/main/java/com/listywave/collection/repository/custom/CustomCollectionRepository.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
  src/main/java/com/listywave/common/util/PaginationUtils.java
  src/main/java/com/listywave/list/application/domain/item/Items.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 버그, 기능, 리팩터링

#143 docs: 버그 리포팅 템플릿 작성
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: 문서

#131 feat: 팔로잉, 팔로워 목록 조회의 정렬 기준을 닉네임 사전순으로 변경
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/repository/follow/custom/CustomFollowRepository.java
  src/main/java/com/listywave/user/repository/follow/custom/impl/CustomFollowRepositoryImpl.java
Labels: 기능

#132 feat: 팔로워 삭제 기능 구현
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능

#149 feat: SecretKey를 환경변수로 관리하도록 수정
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 기능

#137 feat: 이벤트 구독 발행 방식의 Alarm 등록, Alarm 리스트 조회, Alarm 읽기 API 구현
  src/main/java/com/listywave/alarm/application/domain/Alarm.java
  src/main/java/com/listywave/alarm/application/domain/AlarmEvent.java
  src/main/java/com/listywave/alarm/application/domain/AlarmType.java
  src/main/java/com/listywave/alarm/application/dto/AlarmListResponse.java
  src/main/java/com/listywave/alarm/application/dto/AlarmResponse.java
  src/main/java/com/listywave/alarm/application/handler/AlarmEventHandler.java
  src/main/java/com/listywave/alarm/application/service/AlarmService.java
  src/main/java/com/listywave/alarm/presentation/controller/AlarmController.java
  src/main/java/com/listywave/alarm/repository/AlarmRepository.java
  src/main/java/com/listywave/alarm/repository/custom/CustomAlarmRepository.java
  src/main/java/com/listywave/alarm/repository/custom/impl/CustomAlarmRepositoryImpl.java
  src/main/java/com/listywave/collaborator/application/dto/CollaboratorSearchResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/image/presentation/controller/ImageController.java
  src/main/java/com/listywave/image/presentation/dto/request/UserImageUpdateRequest.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능, 리팩터링

#150 feat: 만료된 액세스 토큰으로 요청한 경우 예외 발생 로직 추가
  src/main/java/com/listywave/common/exception/GlobalExceptionHandler.java
Labels: 기능

#153 feat: 탐색 페이지에서 최신리스트 top10 -> 무한페이징구현 및 버그 수정
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 버그, 기능, 리팩터링

#157 feat: 히스토리 RUD 구현
  src/main/java/com/listywave/history/application/domain/History.java
  src/main/java/com/listywave/history/application/domain/HistoryItem.java
  src/main/java/com/listywave/history/application/dto/HistorySearchResponse.java
  src/main/java/com/listywave/history/application/service/HistoryService.java
  src/main/java/com/listywave/history/presentation/HistoryController.java
  src/main/java/com/listywave/history/repository/HistoryRepository.java
Labels: 기능, 급함

#158 fix: 리스트 상세 조회 시, 카테고리가 한글로 담기도록 수정
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
Labels: 버그

#159 feat: 리스트 삭제 시, 히스토리 데이터도 삭제되도록 구현
  src/main/java/com/listywave/history/repository/HistoryRepository.java
  src/main/java/com/listywave/list/application/service/ListService.java
Labels: 기능

#166 feat: 댓글/답글 수정 API 구현
  src/main/java/com/listywave/list/application/domain/comment/Comment.java
  src/main/java/com/listywave/list/application/domain/reply/Reply.java
  src/main/java/com/listywave/list/application/dto/ReplyUpdateCommand.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/list/presentation/dto/request/ReplyUpdateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/comment/CommentUpdateRequest.java
Labels: 기능

#169 feat: 내 콜렉션 조회를 카테고리로 필터링할 수 있도록 구현
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/repository/custom/CustomCollectionRepository.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 기능

#152 refactor: 공통 인증 로직 처리 및 ArgumentResolver 구현
  src/main/java/com/listywave/alarm/application/domain/AlarmEvent.java
  src/main/java/com/listywave/alarm/application/service/AlarmService.java
  src/main/java/com/listywave/alarm/presentation/controller/AlarmController.java
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/auth/presentation/AuthController.java
  src/main/java/com/listywave/collaborator/application/service/CollaboratorService.java
  src/main/java/com/listywave/collaborator/presentation/controller/CollaboratorController.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/common/auth/Auth.java
  src/main/java/com/listywave/common/auth/AuthArgumentResolver.java
  src/main/java/com/listywave/common/auth/AuthContext.java
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/common/auth/OptionalAuth.java
  src/main/java/com/listywave/common/auth/OptionalAuthArgumentResolver.java
  src/main/java/com/listywave/common/config/AuthConfig.java
  src/main/java/com/listywave/common/config/EnumMappingConfig.java
  src/main/java/com/listywave/common/config/WebConfig.java
  src/main/java/com/listywave/common/util/UserUtil.java
  src/main/java/com/listywave/history/application/service/HistoryService.java
  src/main/java/com/listywave/history/presentation/HistoryController.java
  src/main/java/com/listywave/image/application/service/ImageService.java
  src/main/java/com/listywave/image/presentation/controller/ImageController.java
  src/main/java/com/listywave/list/application/dto/response/CategoryTypeResponse.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CategoryController.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 리팩터링

#160 feat: 리스트 상세 조회 시, 로그인 여부와 콜렉트 여부에 따라 isCollected 상태를 응답하도록 구현
  src/main/java/com/listywave/list/application/service/ListService.java
Labels: 기능, 리팩터링

#167 feat: RefreshToken 도입
  src/main/java/com/listywave/auth/application/domain/JwtManager.java
  src/main/java/com/listywave/auth/application/dto/LoginResult.java
  src/main/java/com/listywave/auth/application/dto/UpdateTokenResult.java
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/auth/presentation/AuthController.java
  src/main/java/com/listywave/auth/presentation/dto/LoginResponse.java
  src/main/java/com/listywave/auth/presentation/dto/UpdateTokenResponse.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 기능

#171 feat: 트랜딩 조회 API 응답에 ownerNickname, ownerProfileImageUrl 추가
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
Labels: 기능

#172 feat: 유효한 팔로우 요청인지 검증, 스스로를 팔로우하는 경우 검증, 최대 팔로우 수 검증, 팔로잉/팔로워 수 음수로 빠지는 것 방지
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/user/application/domain/User.java
  src/main/java/com/listywave/user/application/service/UserService.java
Labels: 버그, 기능

#173 feat: 리스트 상세 조회 시, 콜라보레이터 응답에 userId를 포함하도록 수정
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
Labels: 기능

#164 feat: 내 알림 전체 확인여부 조회 API 구현
  src/main/java/com/listywave/alarm/application/dto/AlarmCheckResponse.java
  src/main/java/com/listywave/alarm/application/service/AlarmService.java
  src/main/java/com/listywave/alarm/presentation/controller/AlarmController.java
  src/main/java/com/listywave/alarm/repository/AlarmRepository.java
Labels: 기능

#177 feat: 리스트 검색 시, 각 리스트에 대표 이미지 URL 추가하는 기능 구현
  src/main/java/com/listywave/list/application/domain/item/Items.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListSearchResponse.java
Labels: 기능

#178 fix: 리스트 상세 조회 시, 아이템을 순위대로 정렬해서 응답하도록 구현
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
Labels: 버그

#185 refactor: imageService 코드 리펙토링
  src/main/java/com/listywave/image/application/service/ImageService.java
Labels: 리팩터링

#182 feat: 기본 프로필, 배경 이미지 조회 API 구현
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/image/application/domain/DefaultBackgroundImages.java
  src/main/java/com/listywave/image/application/domain/DefaultProfileImages.java
  src/main/java/com/listywave/image/application/dto/response/DefaultBackgroundImageUrlResponse.java
  src/main/java/com/listywave/image/application/dto/response/DefaultProfileImageUrlResponse.java
  src/main/java/com/listywave/image/presentation/controller/ImageController.java
Labels: 기능

#188 fix: 댓글 조회 및 답글 생성 관련 버그 해결
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/resources/application.yml
Labels: 버그, 급함

#189 feat: 리스트 상세 조회 시, collaborators id에 userId 값을 넣는다
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
Labels: 기능

#190 feat: 최초 로그인시 기본 프로필,배경 이미지 랜덤하게 정해지도록 구현
  src/main/java/com/listywave/image/application/domain/DefaultBackgroundImages.java
  src/main/java/com/listywave/image/application/domain/DefaultProfileImages.java
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 기능

#194 refactor: 수정한 필드 값만 요청으로 받아 수정되도록 리팩터링
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 리팩터링

#197 feat: 내 콜렉션에 해당하는 리스트에 대한 카테고리 조회 API
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/repository/custom/CustomCollectionRepository.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
Labels: 기능

#201 fix: 트랜딩, 최근리스트, 검색결과에 비공개 리스트가 나타나는 버그 수정
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
Labels: 버그

#198 feat: 내 피드에서 해당 리스트의 공개/비공개 설정 API 구현
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/presentation/dto/ListVisibilityUpdateRequest.java
Labels: 기능

#205 feat: 중복 로그아웃 예외 처리
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/common/exception/GlobalExceptionHandler.java
  src/main/java/com/listywave/user/application/domain/User.java
Labels: 기능

#206 feat: 콜라보레이터 변경 및 리스트 수정의 인가 권한 변경
  src/main/java/com/listywave/collaborator/application/domain/Collaborator.java
  src/main/java/com/listywave/collaborator/application/domain/Collaborators.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/test/java/com/listywave/collaborator/application/domain/CollaboratorsTest.java
Labels: 기능

#207 fix: 댓글 조회 시, 집계가 잘못되던 문제 해결
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepository.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepositoryImpl.java
Labels: 버그

#208 feat: 리스트 검색 시, 아이템 타이틀과 코멘트도 관련도 검색에 포함하도록 추가
  src/main/java/com/listywave/list/application/domain/item/Item.java
  src/main/java/com/listywave/list/application/domain/item/ItemComment.java
  src/main/java/com/listywave/list/application/domain/item/ItemTitle.java
  src/main/java/com/listywave/list/application/domain/item/Items.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
Labels: 기능

#209 refactor: 리스트 조회와 관련된 API의 응답에 Item을 순위대로 정렬하여 응답하도록 수정
  src/main/java/com/listywave/collection/application/dto/CollectionResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/domain/item/Items.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListSearchResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/user/application/dto/AllListOfUserSearchResponse.java
  src/main/java/com/listywave/user/application/dto/AllUserListsResponse.java
  src/main/java/com/listywave/user/application/dto/FeedListsResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 리팩터링

#212 fix: 카테고리 전체 조회에 카테고리 이미지도 포함되도록 수정
  src/main/java/com/listywave/list/application/domain/category/CategoryType.java
  src/main/java/com/listywave/list/application/domain/category/CategoryTypeConverter.java
  src/main/java/com/listywave/list/application/dto/response/CategoryTypeResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
Labels: 기능, 리팩터링

#213 fix: 탈퇴한 회원의 데이터와 관련된 버그 해결
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/list/repository/reply/CustomReplyRepositoryImpl.java
  src/main/java/com/listywave/user/application/dto/FeedListsResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/repository/user/custom/CustomUserRepository.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
Labels: 버그, 급함

#215 feat: 회원 탈퇴 요청 시 카카오 인증 서버에 로그아웃 요청을 보내도록 구현
  src/main/java/com/listywave/auth/application/service/AuthService.java
  src/main/java/com/listywave/auth/presentation/AuthController.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
Labels: 기능

#217 fix: cursorId를 cursorUpdatedDate로 수정
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/user/application/dto/AllListOfUserSearchResponse.java
Labels: 버그, 급함

#219 fix: 콜렉션 조회에서 이미지 있는 경우 가장 빠른 순위의 대표이미지 한개 가져오도록 수정
  src/main/java/com/listywave/collection/application/dto/CollectionResponse.java
Labels: 리팩터링

#220 readme 파일 수정
  README.md
Labels: 문서
