Repository 8-Sprinters/ListyWave-back, pull requests merged in 2024-10, with the labels that each got.

#300 feat: 리스트 상세 조회 시 가장 최신 댓글 1개를 응답에 포함하도록 구현
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/repository/CommentRepository.java
  src/main/java/com/listywave/list/repository/reply/ReplyRepository.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/list/application/domain/list/ListEntityTest.java
Labels: 기능

#311 infra: gradle-cache-action 버전 업그레이드
  .github/workflows/ci.yml
Labels: 성능, 인프라

#297 feat: 폴더 관련 CRUD API 구현 및 이에 따른 콜렉션 API 변경
  src/main/java/com/listywave/collection/application/domain/Collect.java
  src/main/java/com/listywave/collection/application/domain/Folder.java
  src/main/java/com/listywave/collection/application/domain/FolderName.java
  src/main/java/com/listywave/collection/application/dto/CollectionResponse.java
  src/main/java/com/listywave/collection/application/dto/FindFolderResponse.java
  src/main/java/com/listywave/collection/application/dto/FolderCreateResponse.java
  src/main/java/com/listywave/collection/application/dto/FolderResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/application/service/FolderService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/presentation/controller/FolderController.java
  src/main/java/com/listywave/collection/presentation/dto/FolderCreateRequest.java
  src/main/java/com/listywave/collection/presentation/dto/FolderSelectionRequest.java
  src/main/java/com/listywave/collection/presentation/dto/FolderUpdateRequest.java
  src/main/java/com/listywave/collection/repository/CollectionRepository.java
  src/main/java/com/listywave/collection/repository/FolderRepository.java
  src/main/java/com/listywave/collection/repository/custom/CustomCollectionRepository.java
  src/main/java/com/listywave/collection/repository/custom/CustomFolderRepository.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomFolderRepositoryImpl.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/domain/category/CategoryType.java
  src/main/java/com/listywave/list/application/dto/response/CategoryTypeResponse.java
  src/main/java/com/listywave/user/application/dto/FindFeedListResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/test/java/com/listywave/acceptance/category/CategoryAcceptanceTest.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTest.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/folder/FolderAcceptanceTest.java
  src/test/java/com/listywave/acceptance/folder/FolderAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTestHelper.java
  src/test/java/com/listywave/collaborator/application/domain/CollaboratorsTest.java
  src/test/java/com/listywave/collection/application/domain/FolderNameTest.java
  src/test/java/com/listywave/collection/application/domain/FolderTest.java
  src/test/java/com/listywave/list/application/domain/category/CategoryTypeConverterTest.java
  src/test/java/com/listywave/list/application/domain/category/CategoryTypeTest.java
  src/test/java/com/listywave/list/application/domain/list/ListEntityTest.java
Labels: 기능, 테스트

#309 feat: 멘션 CRUD 기능 구현
  src/main/java/com/listywave/common/config/QuerydslConfig.java
  src/main/java/com/listywave/common/config/WebConfig.java
  src/main/java/com/listywave/common/exception/CustomException.java
  src/main/java/com/listywave/common/exception/ErrorResponse.java
  src/main/java/com/listywave/common/util/DataUpdateUtils.java
  src/main/java/com/listywave/list/application/domain/comment/Comment.java
  src/main/java/com/listywave/list/application/domain/reply/Reply.java
  src/main/java/com/listywave/list/application/dto/ReplyUpdateCommand.java
  src/main/java/com/listywave/list/application/dto/response/CommentFindResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListRecentResponse.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/presentation/controller/ReplyController.java
  src/main/java/com/listywave/list/presentation/dto/request/ReplyCreateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/ReplyUpdateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/comment/CommentCreateRequest.java
  src/main/java/com/listywave/list/presentation/dto/request/comment/CommentUpdateRequest.java
  src/main/java/com/listywave/list/repository/comment/CommentRepository.java
  src/main/java/com/listywave/list/repository/comment/CustomCommentRepository.java
  src/main/java/com/listywave/list/repository/comment/CustomCommentRepositoryImpl.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/mention/Mention.java
  src/main/java/com/listywave/mention/MentionRepository.java
  src/main/java/com/listywave/mention/MentionService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTest.java
  src/test/java/com/listywave/acceptance/comment/CommentAcceptanceTest.java
  src/test/java/com/listywave/acceptance/comment/CommentAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/acceptance/reply/ReplyAcceptanceTest.java
  src/test/java/com/listywave/common/IntegrationTest.java
  src/test/java/com/listywave/list/application/domain/comment/CommentTest.java
  src/test/java/com/listywave/list/application/domain/reply/ReplyTest.java
  src/test/java/com/listywave/mention/MentionServiceTest.java
  src/test/java/com/listywave/user/fixture/UserFixture.java
Labels: 기능

#315 feat: 알람 ver3.0 구현
  src/main/java/com/listywave/alarm/application/domain/Alarm.java
  src/main/java/com/listywave/alarm/application/domain/AlarmCreateEvent.java
  src/main/java/com/listywave/alarm/application/domain/AlarmDeleteEvent.java
  src/main/java/com/listywave/alarm/application/domain/AlarmEvent.java
  src/main/java/com/listywave/alarm/application/domain/AlarmType.java
  src/main/java/com/listywave/alarm/application/dto/AlarmFindResponse.java
  src/main/java/com/listywave/alarm/application/dto/AlarmListResponse.java
  src/main/java/com/listywave/alarm/application/dto/AlarmReadResponse.java
  src/main/java/com/listywave/alarm/application/dto/FindAlarmResponse.java
  src/main/java/com/listywave/alarm/application/handler/AlarmEventHandler.java
  src/main/java/com/listywave/alarm/application/service/AlarmService.java
  src/main/java/com/listywave/alarm/presentation/controller/AlarmController.java
  src/main/java/com/listywave/alarm/repository/AlarmRepository.java
  src/main/java/com/listywave/alarm/repository/custom/CustomAlarmRepository.java
  src/main/java/com/listywave/alarm/repository/custom/impl/CustomAlarmRepositoryImpl.java
  src/main/java/com/listywave/collection/application/dto/FolderCreateResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/application/service/FolderService.java
  src/main/java/com/listywave/collection/presentation/controller/FolderController.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/list/application/domain/comment/Comment.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/domain/reply/Reply.java
  src/main/java/com/listywave/list/application/service/CommentService.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/application/service/ReplyService.java
  src/main/java/com/listywave/list/presentation/controller/CommentController.java
  src/main/java/com/listywave/list/repository/reply/ReplyRepository.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTest.java
  src/test/java/com/listywave/acceptance/alarm/AlarmAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/alarm/AlarmServiceTest.java
  src/test/java/com/listywave/common/IntegrationTest.java
  src/test/java/com/listywave/mention/MentionServiceTest.java
Labels: 기능

#304 feat: 리액션 API 추가 및 추천리스트 API, 리스트 상세조회 API 재구현
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/dto/response/ListDetailResponse.java
  src/main/java/com/listywave/list/application/dto/response/ListTrandingResponse.java
  src/main/java/com/listywave/list/application/dto/response/RecommendedListResponse.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/list/presentation/controller/ListController.java
  src/main/java/com/listywave/list/repository/list/custom/CustomListRepository.java
  src/main/java/com/listywave/list/repository/list/custom/impl/CustomListRepositoryImpl.java
  src/main/java/com/listywave/reaction/application/domain/Reaction.java
  src/main/java/com/listywave/reaction/application/domain/ReactionStats.java
  src/main/java/com/listywave/reaction/application/domain/UserReaction.java
  src/main/java/com/listywave/reaction/application/dto/response/ReactionResponse.java
  src/main/java/com/listywave/reaction/application/service/ReactionService.java
  src/main/java/com/listywave/reaction/presentation/controller/ReactionController.java
  src/main/java/com/listywave/reaction/presentation/dto/request/ReactionRequest.java
  src/main/java/com/listywave/reaction/repository/ReactionStatsRepository.java
  src/main/java/com/listywave/reaction/repository/UserReactionRepository.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTest.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTest.java
  src/test/java/com/listywave/acceptance/list/ListAcceptanceTestHelper.java
  src/test/java/com/listywave/acceptance/reaction/ReactionAcceptanceTest.java
  src/test/java/com/listywave/acceptance/reaction/ReactionAcceptanceTestHelper.java
Labels: 기능, 테스트

#314 feat: 사용자 추천 API 정책 변경으로 비회원도 사용자 추천 나타나도록 API 수정
  src/main/java/com/listywave/collection/application/dto/CollectionFindResponse.java
  src/main/java/com/listywave/collection/application/service/CollectionService.java
  src/main/java/com/listywave/collection/presentation/controller/CollectionController.java
  src/main/java/com/listywave/collection/repository/custom/impl/CustomCollectionRepositoryImpl.java
  src/main/java/com/listywave/user/application/dto/UsersRecommendedResponse.java
  src/main/java/com/listywave/user/application/service/UserService.java
  src/main/java/com/listywave/user/presentation/UserController.java
  src/main/java/com/listywave/user/repository/user/custom/impl/CustomUserRepositoryImpl.java
  src/test/java/com/listywave/acceptance/collection/CollectionAcceptanceTest.java
  src/test/java/com/listywave/acceptance/user/UserAcceptanceTest.java
  src/test/java/com/listywave/acceptance/user/UserAcceptanceTestHelper.java
Labels: 기능, 테스트

#318 feat: 사용자용 요청 주제(토픽) 생성/조회 API 구현
  src/main/java/com/listywave/common/auth/AuthorizationInterceptor.java
  src/main/java/com/listywave/list/application/domain/category/CategoryType.java
  src/main/java/com/listywave/list/application/domain/category/CategoryTypeConverter.java
  src/main/java/com/listywave/list/application/domain/list/ListEntity.java
  src/main/java/com/listywave/list/application/service/ListService.java
  src/main/java/com/listywave/topic/application/domain/Topic.java
  src/main/java/com/listywave/topic/application/service/TopicService.java
  src/main/java/com/listywave/topic/application/service/dto/ExposedTopicFindResponse.java
  src/main/java/com/listywave/topic/application/service/dto/TopicCreateRequest.java
  src/main/java/com/listywave/topic/presentation/TopicController.java
  src/main/java/com/listywave/topic/repository/CustomTopicRepository.java
  src/main/java/com/listywave/topic/repository/CustomTopicRepositoryImpl.java
  src/main/java/com/listywave/topic/repository/TopicRepository.java
  src/test/java/com/listywave/common/IntegrationTest.java
  src/test/java/com/listywave/topic/application/service/TopicServiceTest.java
Labels: 기능

#320 feat: 관리자용 요청 주제(토픽) 조회 및 수정 API 구현 (#307)
  src/main/java/com/listywave/topic/application/domain/Topic.java
  src/main/java/com/listywave/topic/application/service/TopicService.java
  src/main/java/com/listywave/topic/application/service/dto/TopicFindResponse.java
  src/main/java/com/listywave/topic/presentation/TopicController.java
  src/main/java/com/listywave/topic/presentation/dto/TopicUpdateRequest.java
  src/main/java/com/listywave/topic/repository/CustomTopicRepository.java
  src/main/java/com/listywave/topic/repository/CustomTopicRepositoryImpl.java
  src/main/java/com/listywave/topic/repository/TopicRepository.java
  src/test/java/com/listywave/common/IntegrationTest.java
  src/test/java/com/listywave/topic/application/service/TopicServiceTest.java
Labels: 기능

#323 feat: 공지 CRUD API 구현
  src/main/java/com/listywave/admin/Admin.java
  src/main/java/com/listywave/admin/AdminRepository.java
  src/main/java/com/listywave/admin/AdminService.java
  src/main/java/com/listywave/common/exception/ErrorCode.java
  src/main/java/com/listywave/notice/application/converter/ContentTypeConverter.java
  src/main/java/com/listywave/notice/application/converter/NoticeTypeConverter.java
  src/main/java/com/listywave/notice/application/domain/ContentType.java
  src/main/java/com/listywave/notice/application/domain/Notice.java
  src/main/java/com/listywave/notice/application/domain/NoticeContent.java
  src/main/java/com/listywave/notice/application/domain/NoticeDescription.java
  src/main/java/com/listywave/notice/application/domain/NoticeTitle.java
  src/main/java/com/listywave/notice/application/domain/NoticeType.java
  src/main/java/com/listywave/notice/application/service/NoticeService.java
  src/main/java/com/listywave/notice/application/service/dto/NoticeCreateRequest.java
  src/main/java/com/listywave/notice/application/service/dto/NoticeFindAllResponseToAdmin.java
  src/main/java/com/listywave/notice/application/service/dto/NoticeFindAllResponseToUser.java
  src/main/java/com/listywave/notice/application/service/dto/NoticeFindResponse.java
  src/main/java/com/listywave/notice/application/service/dto/NoticeUpdateRequest.java
  src/main/java/com/listywave/notice/presentation/NoticeController.java
  src/main/java/com/listywave/notice/presentation/dto/NoticeCategoryFindResponse.java
  src/main/java/com/listywave/notice/repository/NoticeRepository.java
  src/test/java/com/listywave/common/IntegrationTest.java
  src/test/java/com/listywave/notice/application/domain/NoticeDescriptionTest.java
  src/test/java/com/listywave/notice/application/domain/NoticeTitleTest.java
  src/test/java/com/listywave/notice/application/domain/NoticeTypeTest.java
  src/test/java/com/listywave/notice/application/service/NoticeServiceTest.java
  src/test/java/com/listywave/topic/application/service/TopicServiceTest.java
Labels: 기능
